# Generated by Django 4.2 on 2026-04-20 14:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_provider', models.CharField(choices=[('AWS', 'AWS'), ('AZURE', 'Azure'), ('GCP', 'GCP')], default='AWS', max_length=20)),
                ('current_region', models.CharField(max_length=50)),
                ('recommended_region', models.CharField(max_length=50)),
                ('current_monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommended_monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbon_profile', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('latency_impact', models.CharField(default='minimal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_optimizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-monthly_savings'],
            },
        ),
        migrations.CreateModel(
            name='IdleResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=100)),
                ('resource_name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('EC2', 'EC2 Instance'), ('RDS', 'RDS Database'), ('Storage', 'Storage Volume'), ('Lambda', 'Lambda Function'), ('ELB', 'Load Balancer')], max_length=20)),
                ('cloud_provider', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=50)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idle_duration_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cpu_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('network_mb_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-monthly_cost'],
            },
        ),
        migrations.CreateModel(
            name='CostSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Simulation', max_length=200)),
                ('base_monthly_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rightsizing_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reserved_savings_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('spot_instances_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('projected_monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('yearly_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily Report'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('CUSTOM', 'Custom Report')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('service_breakdown', models.JSONField(blank=True, default=dict)),
                ('region_breakdown', models.JSONField(blank=True, default=dict)),
                ('tag_breakdown', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagCostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_key', models.CharField(max_length=100)),
                ('tag_value', models.CharField(max_length=200)),
                ('cloud_provider', models.CharField(max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('resource_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('services', models.JSONField(blank=True, default=dict)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_cost_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_cost'],
                'unique_together': {('user', 'tag_key', 'tag_value', 'cloud_provider')},
            },
        ),
    ]
