# Generated by Django 4.2 on 2026-04-11 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('alert_email', models.EmailField(blank=True, max_length=254)),
                ('alert_slack_webhook', models.URLField(blank=True)),
                ('alert_whatsapp', models.CharField(blank=True, max_length=15)),
                ('alert_threshold_percent', models.IntegerField(default=80)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloudlens_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_provider', models.CharField(choices=[('AWS', 'AWS'), ('AZURE', 'Azure'), ('GCP', 'GCP')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action', models.TextField()),
                ('reason', models.TextField()),
                ('estimated_monthly_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_yearly_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('priority_score', models.IntegerField(choices=[(1, 'Low'), (5, 'Medium'), (10, 'High')], default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_score', '-estimated_monthly_savings'],
            },
        ),
        migrations.CreateModel(
            name='CostAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ANOMALY', 'Cost Anomaly'), ('BUDGET', 'Budget Threshold'), ('FORECAST', 'Forecast Warning')], max_length=10)),
                ('cloud_provider', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_change_percent', models.FloatField()),
                ('status', models.CharField(choices=[('TRIGGERED', 'Alert Triggered'), ('SENT', 'Alert Sent'), ('ACKNOWLEDGED', 'User Acknowledged'), ('RESOLVED', 'Resolved')], default='TRIGGERED', max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_to_email', models.BooleanField(default=False)),
                ('sent_to_slack', models.BooleanField(default=False)),
                ('sent_to_whatsapp', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_provider', models.CharField(choices=[('AWS', 'Amazon Web Services'), ('AZURE', 'Microsoft Azure'), ('GCP', 'Google Cloud Platform')], max_length=10)),
                ('date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_costs', models.JSONField(default=dict)),
                ('region_costs', models.JSONField(default=dict)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_billings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'cloud_provider', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CloudCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_provider', models.CharField(choices=[('AWS', 'Amazon Web Services'), ('AZURE', 'Microsoft Azure'), ('GCP', 'Google Cloud Platform')], max_length=10)),
                ('encrypted_key_1', models.TextField()),
                ('encrypted_key_2', models.TextField()),
                ('encrypted_key_3', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('connection_error', models.TextField(blank=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cloud_provider')},
            },
        ),
        migrations.CreateModel(
            name='BillingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_provider', models.CharField(choices=[('AWS', 'Amazon Web Services'), ('AZURE', 'Microsoft Azure'), ('GCP', 'Google Cloud Platform')], max_length=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_costs', models.JSONField(default=list)),
                ('service_costs', models.JSONField(default=dict)),
                ('anomalies', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('is_fresh', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cloud_provider')},
            },
        ),
    ]
