# Generated by Django 4.2 on 2026-04-11 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('ANOMALY', 'Cost Anomaly'), ('BUDGET', 'Budget Threshold'), ('FORECAST', 'Forecast Warning')], max_length=20)),
                ('cloud_provider', models.CharField(max_length=10)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold_unit', models.CharField(default='USD', max_length=20)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_slack', models.BooleanField(default=False)),
                ('notify_whatsapp', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('alert_type', models.CharField(max_length=20)),
                ('cloud_provider', models.CharField(max_length=10)),
                ('triggered_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('TRIGGERED', 'Triggered'), ('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='TRIGGERED', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('slack_sent', models.BooleanField(default=False)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='alerts.alertrule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
